### ISSUE TITLE
Exception on python action plugin code

### ISSUE THREAD

**Issue by arcticlinux** [mmccoo/kicad_mmccoo#10]
When I try to use the Orient the selected modules to underlying graphics, when I have my non straight box placement I get an error.   Sample graphic attached.

![1_4 sample arcs v4](https://user-images.githubusercontent.com/96047/45260671-8612ee80-b3aa-11e8-91e1-fde3d940025e.png)

Exception on python action plugin code

Traceback (most recent call last):

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_plugins.py", line 151, in Run
    break_curves=True)

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_utils.py", line 554, in traverse_graphics
    merged = merge_arcs_and_lines(merge_elts)

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_utils.py", line 329, in merge_arcs_and_lines
    remove_non_duals(e)

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_utils.py", line 307, in remove_non_duals
    remove_non_duals(other)

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_utils.py", line 307, in remove_non_duals
    remove_non_duals(other)

  File "/home/mbest/.kicad_plugins/kicad_mmccoo/dxf_stuff/dxf_utils.py", line 306, in remove_non_duals
    other.other.remove(e)

  File "/usr/lib/python2.7/sets.py", line 518, in remove
    del self._data[element]

KeyError: <kicad_mmccoo.dxf_stuff.dxf_utils.myline instance at 0x7fb16c2bce18>

**Comment by arcticlinux** [comment]
Discovered the problem is there are a ton of extra line segments in my sketch/dxf overlapping in the polygons and the the other.other.remove(e) call in dxf_stuff.dxf_utils.remove_non_duals somehow causes this exception, but if I go and remove the extra line segments it works fine.

**Comment by mmccoo** [comment]
I'm not entirely surprised. I've been wanting to rework some of the polygon
stuff. Any chance I can get a copy of the dxf?

**Comment by arcticlinux** [comment]
I created a minimal test case and test project and included the dxf 
[test.zip](https://github.com/mmccoo/kicad_mmccoo/files/2368030/test.zip)
