### ISSUE TITLE
Place by sch fails with "Exception on python action plugin code"

### ISSUE THREAD

**Issue by 4b11b4** [mmccoo/kicad_mmccoo#11]
KiCad 5.0.1

Traceback (most recent call last):

  File "/home/ab/.kicad_plugins/kicad_mmccoo/place_by_sch/__init__.py", line 15, in Run
    place_by_sch.PlaceBySch()

  File "/home/ab/.kicad_plugins/kicad_mmccoo/place_by_sch/place_by_sch.py", line 105, in PlaceBySch
    locs = parse_eeschema(sch_path)

  File "/home/ab/.kicad_plugins/kicad_mmccoo/place_by_sch/place_by_sch.py", line 95, in parse_eeschema
    orient = orientations[str(t.groups())]

KeyError: "('0', '-1', '1', '0')"

**Comment by 4b11b4** [comment]
Nevermind. This isn't supposed to be run as a plugin...
